cmd_/root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/alg_ags.o := gcc -Wp,-MD,/root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /usr/lib/gcc/arm-linux-gnueabihf/4.9/include -I/usr/src/linux-headers-3.4.112-sun8i/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include /usr/src/linux-headers-3.4.112-sun8i/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-sunxi/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -marm -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=7601U -DRESOURCE_PRE_ALLOC -I/root/TL-WN727N_V4_150909/Driver/MODULE/include -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DADHOC_WPA2PSK_SUPPORT -DWPA_SUPPLICANT_SUPPORT -DWSC_STA_SUPPORT -DWSC_V2_SUPPORT -DWSC_LED_SUPPORT -DIWSC_SUPPORT -DRALINK_ATE -DCONFIG_RT2880_ATE_CMD_NEW -I/root/TL-WN727N_V4_150909/Driver/MODULE/ate/include -DRALINK_QA -DDOT11_N_SUPPORT -DSTATS_COUNT_SUPPORT -DIFUP_IN_PROBE -DOS_ABL_SUPPORT -DOS_ABL_FUNC_SUPPORT -DOS_ABL_OS_PCI_SUPPORT -DOS_ABL_OS_USB_SUPPORT -DOS_ABL_OS_AP_SUPPORT -DOS_ABL_OS_STA_SUPPORT -DEXPORT_SYMTAB -DLED_CONTROL_SUPPORT -DMT7601U -DMT7601 -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRX_DMA_SCATTER -DVCORECAL_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DRTMP_INTERNAL_TX_ALC -DCONFIG_ANDES_SUPPORT -DDPD_CALIBRATION_SUPPORT -DANT_DIVERSITY_SUPPORT -DCONFIG_RX_CSO_SUPPORT -DRTMP_FREQ_CALIBRATION_SUPPORT  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(alg_ags)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7601Usta)" -c -o /root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/.tmp_alg_ags.o /root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/alg_ags.c

source_/root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/alg_ags.o := /root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/alg_ags.c

deps_/root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \
    $(wildcard include/config/ap/support.h) \

/root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/alg_ags.o: $(deps_/root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/alg_ags.o)

$(deps_/root/TL-WN727N_V4_150909/Driver/MODULE/os/linux/../../rate_ctrl/alg_ags.o):
